name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Prisma generate + Typecheck
        run: npx prisma generate && npx tsc --noEmit --pretty false

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
